In [18]:
import nltk
from nltk import word_tokenize

#Corpus de entrenamiento
#tweets que se consideran de polaridad positiva

pos_tweets = ['I love this car.', 'This view is amazing.', 'I feel great this morning', 'I am so excited about the concert', 
             'He is my best friend']

#tweets que se consideran de polaridad negartiva

neg_tweets = ['I do not like this car', 'This view is horrible.', 'I feel tired this morning.','I am not looking forward to the concert.',
             'He is my enemy.']

#Creamos los documentos de entrenamiento

docs = pos_tweets + neg_tweets

print('TRAINING TWEETS', docs)

#Definimos el vectorizador. Las dimensiones del vector que representa una opinion son los valores de relavancia de 
#Las palabras de las opiniones. La metrica para calcular la relevancia es el tf. idf


    
    

TRAINING TWEETS ['I love this car.', 'This view is amazing.', 'I feel great this morning', 'I am so excited about the concert', 'He is my best friend', 'I do not like this car', 'This view is horrible.', 'I feel tired this morning.', 'I am not looking forward to the concert.', 'He is my enemy.']


In [19]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

vectorizer = CountVectorizer(
        analyzer = 'word', #PUEDE TENER UNA FUNCION EN LA QUE DEFINO CUALES SON LOS DATOS QUE INTERESAN
)

In [20]:
print(vectorizer.vocabulary)

X = vectorizer.fit_transform(docs)

print("TRAINING MATRIX")
X_train = X.toarray() #matriz con los vectores de entrenamiento
print(X_train)

None
TRAINING MATRIX
[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0]
 [0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0]]


In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

vectorizer = TfidfVectorizer(
        analyzer = 'word', #PUEDE TENER UNA FUNCION EN LA QUE DEFINO CUALES SON LOS DATOS QUE INTERESAN
)

#Entrenamiento

data_labels = []

for i in range(len(pos_tweets)):
    data_labels.append('POS')           #Data Labelling

for i in range(len(neg_tweets)):
    data_labels.append('NEG')
    
print('TRAINING DATA LABELS', data_labels)

X = vectorizer.fit_transform(docs)

print("TRAINING MATRIX")
X_train = X.toarray() #matriz con los vectores de entrenamiento
print(X_train)

TRAINING DATA LABELS ['POS', 'POS', 'POS', 'POS', 'POS', 'NEG', 'NEG', 'NEG', 'NEG', 'NEG']
TRAINING MATRIX
[[0.         0.         0.         0.         0.59948298 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.7051983  0.         0.         0.         0.         0.
  0.37857035 0.         0.         0.        ]
 [0.         0.         0.63912921 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.42261065 0.         0.
  0.         0.         0.         0.         0.         0.
  0.3431026  0.         0.         0.54331822]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.51416966 0.         0.
  0.60484047 0.         0.         0.         0.         0.
  0.         0.51416966 0.         0.         0.         0.
  0.32469544 0.         0.         0.        ]
 [0.43988604 0.37394332 0.     

In [23]:

y_train = data_labels
import sklearn.svm

classifier = sklearn.svm.LinearSVC() #definimos el clasificador
#aplicar el algoritmo de svm a los datos de entrenamiento
svm_model = classifier.fit(X=X_train, y=y_train) #donde x_train es la matriz con los vectores cada vector es una opinion
                                                    #y_train son los outcomes las valoraciones

new_opinions = ['This movie is horrible', 'The actor is wonderful and very handsome']

#vectorizar las nuevas opiniones

X1 = vectorizer.transform(new_opinions)

#Predecir a  polaridad de las nuevas opiniones

y_pred = svm_model.predict(X1)

print(y_pred)

['NEG' 'POS']
